<ul class="sidebar-menu">
                        <li style="display: none">
                            <a href="../../index.html">
                                <i class="fa fa-dashboard"></i> <span>Dashboard</span>
                            </a>
                        </li>
                       
                     
                          <?php    //if ($this->fk_perfil!=2)
                          	if(count($this->listaMenuProjeto)>0){
?>  
                          <li class="treeview">
                            <a href="#">
                                <i class="fa fa-th"></i>
                                <span>Projeto</span>
                                <i class="fa fa-angle-left pull-right"></i>
                            </a>
                            <ul class="treeview-menu">
                             <?php if(count($this->listaMenuProjeto)>0){
											foreach($this->listaMenuProjeto as $value) : ?>
								<li><a href="<?php echo $this->url(array('controller'=>'index','action'=>$value["NM_PAGINA"]),null, true);?>"><i class="fa fa-angle-double-right"></i><?php echo $value["DS_PAGINA"]?></a></li>
                               <!--  <li><a href="<?php echo $this->url(array('controller'=>'index','action'=>'add-projeto'),null, true);?>"><i class="fa fa-angle-double-right"></i>Adicionar Projeto</a></li>
                                <li><a href="<?php echo $this->url(array('controller'=>'index','action'=>'lista-projeto'),null, true);?>"><i class="fa fa-angle-double-right"></i>Listar Projeto</a></li>
                                <li><a href="<?php echo $this->url(array('controller'=>'index','action'=>'lista-tipo-projeto'),null, true);?>"><i class="fa fa-angle-double-right"></i>Listar Tipo Projeto</a></li>
                                <li><a href="<?php echo $this->url(array('controller'=>'index','action'=>'add-tipo-projeto'),null, true);?>"><i class="fa fa-angle-double-right"></i>Adicionar Tipo Projeto</a></li>
                            	<li><a href="<?php echo $this->url(array('controller'=>'index','action'=>'lista-status-projeto'),null, true);?>"><i class="fa fa-angle-double-right"></i>Listar Status Projeto</a></li>
                                <li><a href="<?php echo $this->url(array('controller'=>'index','action'=>'add-status-projeto'),null, true);?>"><i class="fa fa-angle-double-right"></i>Adicionar Status Projeto</a></li>
                            -->
                            <?php endforeach; }?> 
                            </ul>
                        </li> 
                        <?php }?>
                        <?php    //if ($this->fk_perfil!=2)
                          	if(count($this->listaMenuServicoPcp)>0){
?>  
                          <li class="treeview">
                            <a href="#">
                                <i class="fa fa-th"></i>
                                <span>Serviço/PCP</span>
                                <i class="fa fa-angle-left pull-right"></i>
                            </a>
                            <ul class="treeview-menu">
                             <?php if(count($this->listaMenuServicoPcp)>0){
											foreach($this->listaMenuServicoPcp as $value) : ?>
								<li><a href="<?php echo $this->url(array('controller'=>'index','action'=>$value["NM_PAGINA"]),null, true);?>"><i class="fa fa-angle-double-right"></i><?php echo $value["DS_PAGINA"]?></a></li>
                               
                         
                            <?php endforeach; }?> 
                            </ul>
                        </li> 
                        <?php }?>
                       <!--  <li class="treeview">
                            <a href="#">
                                <i class="fa fa-th"></i>
                                <span>Serviço/PCP</span>
                                <i class="fa fa-angle-left pull-right"></i>
                            </a>
                            <ul class="treeview-menu">
                            	<li><a href="<?php echo $this->url(array('controller'=>'index','action'=>'lista-servico'),null, true);?>"><i class="fa fa-angle-double-right"></i>Listar Serviço</a></li>
                                <li><a href="<?php echo $this->url(array('controller'=>'index','action'=>'add-servico'),null, true);?>"><i class="fa fa-angle-double-right"></i>Adicionar Serviço</a></li>
                                <li><a href="<?php echo $this->url(array('controller'=>'index','action'=>'lista-tipo-servico'),null, true);?>"><i class="fa fa-angle-double-right"></i>Listar Tipo Serviço/PCP</a></li>
                                <li><a href="<?php echo $this->url(array('controller'=>'index','action'=>'add-tipo-servico'),null, true);?>"><i class="fa fa-angle-double-right"></i>Adicionar Tipo Serviço/PCP</a></li>
                                <li><a href="<?php echo $this->url(array('controller'=>'index','action'=>'lista-pcp'),null, true);?>"><i class="fa fa-angle-double-right"></i>Listar Pcp</a></li>
                                <li><a href="<?php echo $this->url(array('controller'=>'index','action'=>'add-pcp'),null, true);?>"><i class="fa fa-angle-double-right"></i>Adicionar Pcp</a></li>
                                
                            </ul>
                        </li>-->
                       
                       
                        <!-- <li class="treeview">
                            <a href="#">
                                <i class="fa fa-th"></i>
                                <span>Meus Planos de ação</span>
                                <i class="fa fa-angle-left pull-right"></i>
                            </a>
                            <ul class="treeview-menu">
                            <li><a href="<?php echo $this->url(array('controller'=>'index','action'=>'lista-plano-acao'),null, true);?>"><i class="fa fa-angle-double-right"></i>Listar PA</a></li>
                                <li><a href="<?php echo $this->url(array('controller'=>'index','action'=>'add-plano-acao'),null, true);?>"><i class="fa fa-angle-double-right"></i>Adicionar PA</a></li>
                                 
                                
                            </ul>
                        </li> -->
                         <?php    //if ($this->fk_perfil!=2)
                          	if(count($this->listaMenuPlanoAcao)>0){
?>  
                          <li class="treeview">
                            <a href="#">
                                <i class="fa fa-th"></i>
                                <span>Meus Planos de ação</span>
                                <i class="fa fa-angle-left pull-right"></i>
                            </a>
                            <ul class="treeview-menu">
                             <?php if(count($this->listaMenuPlanoAcao)>0){
											foreach($this->listaMenuPlanoAcao as $value) : ?>
								<li><a href="<?php echo $this->url(array('controller'=>'index','action'=>$value["NM_PAGINA"]),null, true);?>"><i class="fa fa-angle-double-right"></i><?php echo $value["DS_PAGINA"]?></a></li>
                               
                         
                            <?php endforeach; }?> 
                            </ul>
                        </li> 
                        <?php }?>
                         <?php    //if ($this->fk_perfil!=2)
                          	if(count($this->listaMenuContato)>0){
?>  
                          <li class="treeview">
                            <a href="#">
                                <i class="fa fa-th"></i>
                                <span>Contato</span>
                                <i class="fa fa-angle-left pull-right"></i>
                            </a>
                            <ul class="treeview-menu">
                             <?php if(count($this->listaMenuContato)>0){
											foreach($this->listaMenuContato as $value) : ?>
								<li><a href="<?php echo $this->url(array('controller'=>'index','action'=>$value["NM_PAGINA"]),null, true);?>"><i class="fa fa-angle-double-right"></i><?php echo $value["DS_PAGINA"]?></a></li>
                               
                         
                            <?php endforeach; }?> 
                            </ul>
                        </li> 
                        <?php }?>
                        <!--  <li class="treeview">
                            <a href="#">
                                <i class="fa fa-th"></i>
                                <span>Contato</span>
                                <i class="fa fa-angle-left pull-right"></i>
                            </a>
                            <ul class="treeview-menu">
								<li><a href="<?php echo $this->url(array('controller'=>'index','action'=>'lista-contato'),null, true);?>"><i class="fa fa-angle-double-right"></i>Listar Contato</a></li>
                                <li><a href="<?php echo $this->url(array('controller'=>'index','action'=>'add-contato'),null, true);?>"><i class="fa fa-angle-double-right"></i>Adicionar Contato</a></li>
                                
                                
                            </ul>
                        </li>-->
                        <?php //}?>
                        <!--   <?php    if ($this->fk_perfil==1){?>  <li class="treeview">
                            <a href="#">
                                <i class="fa fa-th"></i>
                                <span>Operador</span>
                                <i class="fa fa-angle-left pull-right"></i>
                            </a>
                            <ul class="treeview-menu">
                                <li><a href="<?php echo $this->url(array('controller'=>'index','action'=>'lista-operador'),null, true);?>"><i class="fa fa-angle-double-right"></i> Listar Operador</a></li>
                                <li><a href="<?php echo $this->url(array('controller'=>'index','action'=>'lista-operador-simples'),null, true);?>"><i class="fa fa-angle-double-right"></i> Listar Operador(Simples)</a></li>
                                <li><a href="<?php echo $this->url(array('controller'=>'index','action'=>'add-operador'),null, true);?>"><i class="fa fa-angle-double-right"></i> Adicionar Operador</a></li>
                                
                            </ul>
                        </li> <?php }?>
                        -->
                        <?php    //if ($this->fk_perfil!=2)
                          	if(count($this->listaMenuOperador)>0){
?>  
                          <li class="treeview">
                            <a href="#">
                                <i class="fa fa-th"></i>
                                <span>Operador</span>
                                <i class="fa fa-angle-left pull-right"></i>
                            </a>
                            <ul class="treeview-menu">
                             <?php if(count($this->listaMenuOperador)>0){
											foreach($this->listaMenuOperador as $value) : ?>
								<li><a href="<?php echo $this->url(array('controller'=>'index','action'=>$value["NM_PAGINA"]),null, true);?>"><i class="fa fa-angle-double-right"></i><?php echo $value["DS_PAGINA"]?></a></li>
                               
                         
                            <?php endforeach; }?> 
                            </ul>
                        </li> 
                        <?php }?>
                        
                         <?php    //if ($this->fk_perfil!=2)
                          	if(count($this->listaMenuCliente)>0){
?>  
                          <li class="treeview">
                            <a href="#">
                                <i class="fa fa-th"></i>
                                <span>Cliente</span>
                                <i class="fa fa-angle-left pull-right"></i>
                            </a>
                            <ul class="treeview-menu">
                             <?php if(count($this->listaMenuCliente)>0){
											foreach($this->listaMenuCliente as $value) : ?>
								<li><a href="<?php echo $this->url(array('controller'=>'index','action'=>$value["NM_PAGINA"]),null, true);?>"><i class="fa fa-angle-double-right"></i><?php echo $value["DS_PAGINA"]?></a></li>
                               
                         
                            <?php endforeach; }?> 
                            </ul>
                        </li> 
                        <?php }?>
						<!--  <li class="treeview">
                            <a href="#">
                                <i class="fa fa-th"></i>
                                <span>Cliente</span>
                                <i class="fa fa-angle-left pull-right"></i>
                            </a>
                            <ul class="treeview-menu">
								<li><a href="<?php echo $this->url(array('controller'=>'index','action'=>'lista-ramo-atividade'),null, true);?>"><i class="fa fa-angle-double-right"></i>Listar Ramo de Atividade</a></li>
                                <li><a href="<?php echo $this->url(array('controller'=>'index','action'=>'add-ramo-atividade'),null, true);?>"><i class="fa fa-angle-double-right"></i>Adicionar Ramo de Atividade</a></li>
                                <li><a href="<?php echo $this->url(array('controller'=>'index','action'=>'lista-cliente'),null, true);?>"><i class="fa fa-angle-double-right"></i>Listar Cliente</a></li>
                                <li><a href="<?php echo $this->url(array('controller'=>'index','action'=>'add-cliente'),null, true);?>"><i class="fa fa-angle-double-right"></i>Adicionar Cliente</a></li>
                                
                            </ul>
                        </li>-->
                        <!--<?php    if ($this->fk_perfil==1){?>  <li class="treeview">
                            <a href="#">
                                <i class="fa fa-th"></i>
                                <span>Notícia</span>
                                <i class="fa fa-angle-left pull-right"></i>
                            </a>
                            <ul class="treeview-menu">
                                <li><a href="<?php echo $this->url(array('controller'=>'index','action'=>'lista-noticia'),null, true);?>"><i class="fa fa-angle-double-right"></i> Listar Notícia</a></li>
                                <li><a href="<?php echo $this->url(array('controller'=>'index','action'=>'add-noticia'),null, true);?>"><i class="fa fa-angle-double-right"></i> Adicionar Notícia</a></li>
                                
                            </ul>
                        </li> <?php }?>-->
                        <?php    //if ($this->fk_perfil!=2)
                          	if(count($this->listaMenuNoticia)>0){
?>  
                          <li class="treeview">
                            <a href="#">
                                <i class="fa fa-th"></i>
                                <span>Notícia</span>
                                <i class="fa fa-angle-left pull-right"></i>
                            </a>
                            <ul class="treeview-menu">
                             <?php if(count($this->listaMenuNoticia)>0){
											foreach($this->listaMenuNoticia as $value) : ?>
								<li><a href="<?php echo $this->url(array('controller'=>'index','action'=>$value["NM_PAGINA"]),null, true);?>"><i class="fa fa-angle-double-right"></i><?php echo $value["DS_PAGINA"]?></a></li>
                               
                         
                            <?php endforeach; }?> 
                            </ul>
                        </li> 
                        <?php }?>
                        <!--  
                        <li class="treeview">
                            <a href="#">
                                <i class="fa fa-th"></i>
                                <span>Configuração</span>
                                <i class="fa fa-angle-left pull-right"></i>
                            </a>
                            <ul class="treeview-menu">
								<li><a href="<?php echo $this->url(array('controller'=>'index','action'=>'permissao'),null, true);?>"><i class="fa fa-angle-double-right"></i>Permissão</a></li>
                               
                                
                            </ul>
                        </li>-->
                        <?php    //if ($this->fk_perfil!=2)
                          	if(count($this->listaMenuConfiguracao)>0){
?>  
                          <li class="treeview">
                            <a href="#">
                                <i class="fa fa-th"></i>
                                <span>Configurações</span>
                                <i class="fa fa-angle-left pull-right"></i>
                            </a>
                            <ul class="treeview-menu">
                             <?php if(count($this->listaMenuConfiguracao)>0){
											foreach($this->listaMenuConfiguracao as $value) : ?>
								<li><a href="<?php echo $this->url(array('controller'=>'index','action'=>$value["NM_PAGINA"]),null, true);?>"><i class="fa fa-angle-double-right"></i><?php echo $value["DS_PAGINA"]?></a></li>
                               
                         
                            <?php endforeach; }?> 
                            </ul>
                        </li> 
                        <?php }?>
                       
                    </ul>
