
INSERT INTO `TB_RAMO_ATIVIDADE` (`ID_RAMO_ATIVIDADE`, `DS_RAMO_ATIVIDADE`) VALUES
(7, 'Atividades Agrossilvipastoris'),
(5, 'Atividades de Infra-Estrutura'),
(48, 'Atividades Imobiliarias'),
(1, 'Atividades Minerárias'),
(35, 'Cemitério'),
(9, 'Empresas de Consultoria'),
(10, 'Empresas públicas e Prefeituras'),
(8, 'Geral'),
(3, 'Indústira Química'),
(4, 'Indústria Alimentícia e Bebidas'),
(36, 'Indústria Autopeças'),
(49, 'Indústria Eletro Eletronica'),
(11, 'Industria Gráfica'),
(2, 'Indústria Metalúrgica'),
(50, 'Lavanderia Industrial'),
(51, 'PEQUI AMBIENTAL'),
(29, 'Posto de Gasolina'),
(31, 'Serviços de Saude'),
(6, 'Serviços e Comércio Atacadista'),
(32, 'Serviços Educacionais'),
(30, 'Transportes e Logistica'),
(40, 'Usina Hidreletrica');
