
INSERT INTO `TB_STATUS_PROJETO` (`ID_STATUS_PROJETO`, `NM_STATUS_PROJETO`) VALUES
(1, 'DEMANDA CADASTRADA'),
(2, 'ANÁLISE DE VIABILIDADE TÉCNICA'),
(3, '* PERMANENTE'),
(4, '* CONCLUÍDO COM SUCESSO'),
(5, '* ARQUIVADO'),
(6, 'EM ANÁLISE AGÊNCIA AMBIENTAL'),
(7, '* SUSPENSO TEMPORARIAMENTE'),
(8, 'EM ANDAMENTO BIOS'),
(9, 'AGUARDA RESPOSTA DO CLIENTE'),
(10, '* CANCELADO - NÃO APROVADO'),
(11, 'AGUARDANDO APROV. DA DIRETORIA'),
(12, 'PRIORITÁRIO'),
(13, 'ACOMPANHAMENTO FINANCEIRO'),
(14, 'CONTRATATAÇÃO'),
(15, 'enviado para aprovação cliente');
