
INSERT INTO `TB_TIPO_PROJETO` (`ID_TIPO_PROJETO`, `NM_TIPO_PROJETO`) VALUES
(1, 'LO - Licença de operação'),
(2, 'LOC - Lic Operac.Corretiva'),
(3, 'Gestão de Informação'),
(4, 'AAF AUTORIZ AMBIENTAL FUNCIONA'),
(5, 'PTRF Projeto Tec Rec da Flora'),
(6, 'APEF -Autorizacao Expl. Flores'),
(7, 'Educação Ambiental'),
(9, 'Licença de Adequação - PBH'),
(10, 'Outorga Uso Recursos Hidricos'),
(11, 'PROPOSTA COMERCIAL'),
(12, 'Plano Diretor Participativo'),
(14, 'Implantaçao DocManager'),
(15, 'Outorga - água subterrânea'),
(16, 'Outorga - água superficial'),
(17, 'LP - Licença Prévia '),
(18, 'Licitação'),
(19, 'Legislação Ambiental'),
(20, 'Renovação de Licença Ambiental'),
(21, 'Consultoria SGA'),
(22, 'CTF Cadastro Técnico Federal'),
(23, 'LI - Licença de Instalação'),
(24, 'Informações Técnicas'),
(25, 'Pautas COPAM'),
(26, 'ProjetoTécnico'),
(27, 'Auditoria SGA / SGI'),
(28, 'Monitoramento Ambiental'),
(29, 'Defesa Auto de Infração'),
(30, 'T 187 Copasa'),
(31, 'GERAL '),
(32, 'Controle de Contratos'),
(33, 'Pautas COPAM'),
(34, 'RNC Registro Nao Conformidade'),
(35, 'Averbação Reserva Legal'),
(36, 'Treinamento'),
(37, 'Plano de Fechamento'),
(38, 'RIC  Relat Impacto Viário'),
(45, 'PGRSS - Prog Gest Res Saúde'),
(46, 'Averbação Reserva Legal'),
(47, 'EIA - RIMA'),
(48, 'Regularizaçao SEDRU'),
(49, 'PROPOSTA COMERCIAL BIOSLAB'),
(50, 'Medição Ruído BiosLab'),
(51, 'Certificação ISO 17.025'),
(52, 'Estudo Arqueologico'),
(53, 'EIV Estudo de Impacto Vizinhan'),
(54, 'Inventario Flora/Fauna'),
(55, 'PRAD - Plano de Recuperacao '),
(56, 'Assessoria Ambiental'),
(57, 'Projeto Silviculturais'),
(58, 'LP + LI'),
(59, 'PEQUI'),
(60, 'gestão bios'),
(61, 'ADMINISTRATIVO'),
(62, 'regularização ambiental'),
(63, 'Administrativo'),
(64, 'RIU RELAT IMPACTO VIZINHANÇA'),
(65, 'SISCAR/CAR'),
(66, 'cadastro car/sicar'),
(67, 'PLANTIO FLORESTAL');

