
<?php
	$this->title = "Deletar Tipo Projeto";
	$this->headTitle($this->title);
?>

<div class="callout callout-danger">
                                        <h4>Atenção!</h4>
                                        Deseja realmente deletar  '<?php echo $this->escape($this->tipoProjeto['NM_TIPO_PROJETO']);?>' ?
                                    </div>
<form action="<?php echo $this->url(array('action' => 'lista-tipo-projeto'),null, true);?>" method="post">
	<div>
		<input type="hidden" name="ID_TIPO_PROJETO" value="<?php echo $this->tipoProjeto['ID_TIPO_PROJETO'];?>" /> 
		
	</div>
	<div class="form-group">
                                        		
<input type="submit" class="btn btn-primary"name="del" value="Sim">                                        		
<input type="submit" class="btn btn-primary"    name="del" value="Não">                                        		

                                    		</div>
</form>
