
<?php
	$this->title = "Deletar Notícia";
	$this->headTitle($this->title);
?>

<div class="callout callout-danger">
                                        <h4>Atenção!</h4>
                                        Deseja realmente deletar  '<?php echo $this->escape($this->noticia['DS_TITULO']);?>' ?
                                    </div>
<form action="<?php echo $this->url(array('action' => 'lista-noticia'),null, true);?>" method="post">
	<div>
		<input type="hidden" name="ID_NOTICIA" value="<?php echo $this->noticia['ID_NOTICIA'];?>" /> 
		
	</div>
	<div class="form-group">
                                        		
<input type="submit" class="btn btn-primary"name="del" value="Sim">                                        		
<input type="submit" class="btn btn-primary"    name="del" value="Não">                                        		

                                    		</div>
</form>
