
<?php
	$this->title = "Deletar Operador";
	$this->headTitle($this->title);
?>

<div class="callout callout-danger">
                                        <h4>Atenção!</h4>
                                        Deseja realmente deletar o operador  '<?php echo $this->escape($this->operador['NM_OPERADOR']);?>' do projeto '<?php echo $this->escape($this->projeto['NM_PROJETO']);?>'?
                                    </div>
<form action="<?php echo $this->url(array('action' => 'lista-projeto-operador', 'id'=>$this->projeto['ID_PROJETO']),null, true);?>" method="post">
	<div>
		<input type="hidden" name="FK_OPERADOR" value="<?php echo $this->operador['ID_OPERADOR'];?>" />
		<input type="hidden" name="FK_PROJETO" value="<?php echo $this->projeto['ID_PROJETO'];?>" />  
		
	</div>
	<div class="form-group">
                                        		
<input type="submit" class="btn btn-primary" id="submitbutton" name="del" value="Sim">                                        		
<input type="submit" class="btn btn-primary"   id="vincularReferencia" name="del" value="Não">                                        		

                                    		</div>
</form>
