
<?php
	$this->title = "Deletar Operador";
	$this->headTitle($this->title);
?>

<div class="callout callout-danger">
                                        <h4>Atenção!</h4>
                                        Deseja realmente deletar  '<?php echo $this->escape($this->operador['NM_OPERADOR']);?>' E-mail Bios '<?php echo $this->escape($this->operador['DS_EMAIL_BIOS']);?>'?
                                    </div>
<form action="<?php echo $this->url(array('action' => 'lista-operador'),null, true);?>" method="post">
	<div>
		<input type="hidden" name="ID_OPERADOR" value="<?php echo $this->operador['ID_OPERADOR'];?>" /> 
		
	</div>
	<div class="form-group">
                                        		
<input type="submit" class="btn btn-primary" id="submitbutton" name="del" value="Sim">                                        		
<input type="submit" class="btn btn-primary"   id="vincularReferencia" name="del" value="Não">                                        		

                                    		</div>
</form>
