<?php
	$this->title = "Listar Projeto";
	$this->headTitle($this->title);
	//echo $this->form ;
	
?>

<div class="box">
                                <div class="box-header">
                                    <h3 class="box-title">Lista Projeto</h3>
                                </div><!-- /.box-header -->
                                <div class="box-body">                                
                                    <table id="example1" class="table table-bordered table-hover box-body table-responsive no-padding">
                                        <thead>
                                            <tr>
                                                <th class="arredondarEsq">OPER</th>
												<th >PA</th>
												<th>CONTATOS</th>
												<th >DOCS</th>
												<th >SERVIÇOS</th>
												<th >PCP</th>
												<th >CLIENTE</th>
												<th >NOME PROJETO</th>
												<th >TIPO</th>
												<th >DATA CADASTRO</th>
												<!--  <th >OBSERVAÇÃO</th>-->
												<th >STATUS</th>
												<th>AÇÃO</th>
                                                
                                            </tr>
                                        </thead>
                                        <tbody>
                                        <?php if(count($this->listaProjetos)>0){
											foreach($this->listaProjetos as $projeto) : ?>
                                            <tr>
                                            <td><a class="btn btn-app" href="<?php echo $this->url(array('controller'=>'index','action'=>'lista-projeto-operador', 'id'=>$projeto["ID_PROJETO"]),null, true);?>"><i class="fa fa-users"></i></a></td>
											<td><a class="btn btn-app" href="<?php echo $this->url(array('controller'=>'index','action'=>'lista-projeto-plano-acao', 'id'=>$projeto["ID_PROJETO"]),null, true);?>"><i class="fa fa-file-text-o"></i></a></td>
											<td><a class="btn btn-app" href="<?php echo $this->url(array('controller'=>'index','action'=>'lista-projeto-contato', 'id'=>$projeto["ID_PROJETO"]),null, true);?>"><i class="fa fa-envelope-o"></i></a></td>
											<td><a class="btn btn-app" ><i class="fa fa-file-o"></i></a></td>
											<td><a class="btn btn-app"  href="<?php echo $this->url(array('controller'=>'index','action'=>'lista-projeto-servico', 'id'=>$projeto["ID_PROJETO"]),null, true);?>"><i class="fa fa-wrench"></i></a></td>
											<td><a class="btn btn-app" href="<?php echo $this->url(array('controller'=>'index','action'=>'lista-projeto-pcp', 'id'=>$projeto["ID_PROJETO"]),null, true);?>"><i class="fa fa-file-text"></i></a></td>
											<td><?php  echo $this->truncate($projeto["NM_CLIENTE"],50)?></td>
											<td><?php  echo $this->truncate($projeto["NM_PROJETO"],50)?></td>
											<td><?php echo $projeto["NM_TIPO_PROJETO"]?></td>
											<td><?php echo $projeto["DT_CADASTRO"]?></td>
											<!--  <td><?php echo $this->truncate($projeto["TX_OBSERVACAO"],50)?></td>-->
											<td><?php echo $projeto["NM_STATUS_PROJETO"]?></td>
                                             <td>
                                             <?php  if($this->permissaoEditProjeto){?>
                                                <a alt="Editar" title="Editar" href="<?php echo $this->url(array('controller'=>'index','action'=>'edit-projeto', 'id'=>$projeto["ID_PROJETO"]),null, true);?>" class="btn-sm btn-warning"><i class="glyphicon glyphicon-edit"></i></a> 
                                                <?php }?> 
                                                <?php  if($this->permissaoDeleteProjeto){?>
                                                 <a alt="Excluir" title="Excluir" href="<?php echo $this->url(array('controller'=>'index','action'=>'delete-projeto', 'id'=>$projeto["ID_PROJETO"]),null, true);?>" class="btn-sm  btn-danger"><i class="glyphicon glyphicon-trash"></i></a>
                                                <?php }?> 
                                                </td>
                                            </tr>
                                          <?php endforeach; ?>
	<?php }?> 
                                        </tbody>
                                        <tfoot>
                                            <tr>
                                                <th class="arredondarEsq">OPERADORES</th>
												<th >PA</th>
												<th>CONTATOS</th>
												<th >DOCS</th>
												<th >SERVIÇOS</th>
												<th >PCP</th>
												<th >CLIENTE</th>
												<th >NOME PROJETO</th>
												<th >TIPO</th>
												<th >DATA CADASTRO</th>
												<!-- <th >OBSERVAÇÃO</th> -->
												<th >STATUS</th>
												<th>AÇÃO</th>
                                                                                             
                                            </tr>
                                        </tfoot>
                                    </table>
                                </div><!-- /.box-body -->
                            </div><!-- /.box -->
                            <?php  if($this->permissaoAdicionarProjeto){?>
                            <div class="form-group">
                                 <a alt="Adicionar" title="Adicionar" style="font-family: inherit;" href="<?php echo $this->url(array('controller'=>'index','action'=>'add-projeto'),null, true);?>" class="btn-sm  "><i class="btn btn-primary">Adicionar Projeto</i></a>   		
                                     		

                                    		</div>
                             <?php }?> 
<link href="<?php echo $this->baseUrl()?>/plugins/datatables/dataTables.bootstrap.css" rel="stylesheet" type="text/css" />
<script src="<?php echo $this->baseUrl()?>/plugins/datatables/jquery.dataTables.min.js" ></script>
<script src="<?php echo $this->baseUrl()?>/plugins/datatables/dataTables.bootstrap.min.js" ></script>
<!-- page script -->
<script type="text/javascript">
            $(function() {
                $("#example1").dataTable();
				$("#example2").dataTable();
                /*$('#example2').dataTable({
                    "bPaginate": true,
                    "bLengthChange": false,
                    "bFilter": true,
                    "bSort": true,
                    "bInfo": true,
                    "bAutoWidth": false
                });*/
            });
</script>
