<?php
	$this->title = "Listar Contato";
	$this->headTitle($this->title);
	//echo $this->form ;
	
?>

<div class="box">
                                <div class="box-header">
                                    <h3 class="box-title">Lista Contato</h3>
                                </div><!-- /.box-header -->
                                <div class="box-body">                                
                                    <table id="example1" class="table table-bordered table-hover">
                                        <thead>
                                            <tr>
                                                <th class="arredondarEsq">NOME</th>
												<th >CARGO</th>
												<th>Telefone 1</th>
												<th >E-MAIL</th>
												<th >CLIENTE</th>
												
												<th>AÇÃO</th>
                                                
                                            </tr>
                                        </thead>
                                        <tbody>
                                        <?php if(count($this->contatos)>0){
											foreach($this->contatos as $contatos) : ?>
                                            <tr>
                                            <td><?php echo $contatos["NM_CONTATO"]?></td>
											<td><?php echo $contatos["NM_CARGO"]?></td>
											<td><?php echo $contatos["NR_TELEFONE"]?></td>
											<td><?php echo $contatos["DS_EMAIL"]?></td>
                                             <td><?php echo $contatos["NM_CLIENTE"]?></td>
                                             <td>
                                                <a alt="Editar" title="Editar" href="<?php echo $this->url(array('controller'=>'index','action'=>'edit-contato', 'id'=>$contatos["ID_CONTATO"]),null, true);?>" class="btn-sm btn-warning"><i class="glyphicon glyphicon-edit"></i></a> 
                                                 <a alt="Excluir" title="Excluir" href="<?php echo $this->url(array('controller'=>'index','action'=>'delete-contato', 'id'=>$contatos["ID_CONTATO"]),null, true);?>" class="btn-sm  btn-danger"><i class="glyphicon glyphicon-trash"></i></a>
                                                
                                                </td>
                                            </tr>
                                          <?php endforeach; ?>
	<?php }?> 
                                        </tbody>
                                        <tfoot>
                                            <tr>
                                                <th class="arredondarEsq">NOME</th>
												<th >CARGO</th>
												<th>Telefone 1</th>
												<th >E-MAIL</th>
												<th >CLIENTE</th>
												<th>AÇÃO</th>                                               
                                            </tr>
                                        </tfoot>
                                    </table>
                                </div><!-- /.box-body -->
                            </div><!-- /.box -->
                            <div class="form-group">
                                 <a alt="Adicionar" title="Adicionar" style="font-family: inherit;" href="<?php echo $this->url(array('controller'=>'index','action'=>'add-contato'),null, true);?>" class="btn-sm  "><i class="btn btn-primary">Adicionar Operador</i></a>   		
                                     		

                                    		</div>
<link href="<?php echo $this->baseUrl()?>/plugins/datatables/dataTables.bootstrap.css" rel="stylesheet" type="text/css" />
<script src="<?php echo $this->baseUrl()?>/plugins/datatables/jquery.dataTables.min.js" ></script>
<script src="<?php echo $this->baseUrl()?>/plugins/datatables/dataTables.bootstrap.min.js" ></script>
<!-- page script -->
<script type="text/javascript">
            $(function() {
                $("#example1").dataTable();
				$("#example2").dataTable();
                /*$('#example2').dataTable({
                    "bPaginate": true,
                    "bLengthChange": false,
                    "bFilter": true,
                    "bSort": true,
                    "bInfo": true,
                    "bAutoWidth": false
                });*/
            });
</script>
