<?php
	$this->title = "Listar Contato";
	$this->headTitle($this->title);
	//echo $this->form ;
	
?>

<div class="box">
                                <div class="box-header">
                                    <h3 class="box-title">Lista Plano Acao</h3>
                                </div><!-- /.box-header -->
                                <div class="box-body">                                
                                    <table id="example1" class="table table-bordered table-hover box-body table-responsive no-padding">
                                        <thead>
                                            <tr>
                                                <th class="arredondarEsq">PROJETO</th>
                                                <th >ASSUNTO</th>
												<th >AÇÕES</th>
												<th>ATUALIZACÃO</th>
												<th >OPERADOR</th>
												<th >PREVISÃO</th>
												<th >STATUS</th>
												<th >CONCLUSÃO</th>
												<th >CONTROLE</th>
												<th>AÇÃO</th>
                                                
                                            </tr>
                                        </thead>
                                        <tbody>
                                        <?php if(count($this->planoAcao)>0){
											foreach($this->planoAcao as $planoAcao) : ?>
                                            <tr>
                                            <td><?php  echo $this->truncate($planoAcao["NM_PROJETO"],50)?></td>
                                            <td><?php echo $planoAcao["DS_ASSUNTO"]?></td>
											<td><?php echo $planoAcao["TX_PLANO_ACAO"]?></td>
											<td><?php echo $planoAcao["DT_ATUALIZACAO"]?></td>
											<td><?php echo $planoAcao["PRIMEIRO_NOME"]?></td>
											<td><?php echo $planoAcao["DT_PREVISAO"]?></td>
											<td><?php echo $planoAcao["NM_STATUS_PLANO_ACAO"]?></td>
											<td><?php echo $planoAcao["DT_CONCLUSAO"]?></td>
											<td><?php echo $planoAcao["DT_CONTROLE"]?></td>
											
                                             <td>
                                                <a alt="Editar" title="Editar" href="<?php echo $this->url(array('controller'=>'index','action'=>'edit-plano-acao', 'id'=>$planoAcao["ID_PLANO_ACAO"]),null, true);?>" class="btn-sm btn-warning"><i class="glyphicon glyphicon-edit"></i></a> 
                                                 <a alt="Excluir" title="Excluir" href="<?php echo $this->url(array('controller'=>'index','action'=>'delete-plano-acao', 'id'=>$planoAcao["ID_PLANO_ACAO"]),null, true);?>" class="btn-sm  btn-danger"><i class="glyphicon glyphicon-trash"></i></a>
                                                
                                                </td>
                                            </tr>
                                          <?php endforeach; ?>
	<?php }?> 
                                        </tbody>
                                        <tfoot>
                                            <tr>
                                            	<th class="arredondarEsq">PROJETO</th>
                                                <th >ASSUNTO</th>
												<th >AÇÕES</th>
												<th>ATUALIZACÃO</th>
												<th >OPERADOR</th>
												<th >PREVISÃO</th>
												<th >STATUS</th>
												<th >CONCLUSÃO</th>
												<th >CONTROLE</th>											
												<th>AÇÃO</th>                                          
                                            </tr>
                                        </tfoot>
                                    </table>
                                </div><!-- /.box-body -->
                            </div><!-- /.box -->
                            <div class="form-group">
                                 <a alt="Adicionar" title="Adicionar" style="font-family: inherit;" href="<?php echo $this->url(array('controller'=>'index','action'=>'add-plano-acao'),null, true);?>" class="btn-sm  "><i class="btn btn-primary">Adicionar Plano Ação</i></a>   		
                                     		

                                    		</div>
<link href="<?php echo $this->baseUrl()?>/plugins/datatables/dataTables.bootstrap.css" rel="stylesheet" type="text/css" />
<script src="<?php echo $this->baseUrl()?>/plugins/datatables/jquery.dataTables.min.js" ></script>
<script src="<?php echo $this->baseUrl()?>/plugins/datatables/dataTables.bootstrap.min.js" ></script>
<!-- page script -->
<script type="text/javascript">
            $(function() {
                $("#example1").dataTable();
				$("#example2").dataTable();
                /*$('#example2').dataTable({
                    "bPaginate": true,
                    "bLengthChange": false,
                    "bFilter": true,
                    "bSort": true,
                    "bInfo": true,
                    "bAutoWidth": false
                });*/
            });
</script>
