<?php
	$this->title = "Listar Serviço";
	$this->headTitle($this->title);
	//echo $this->form ;
	
?>

<div class="box">
                                <div class="box-header">
                                    <h3 class="box-title">Lista Serviço</h3>
                                </div><!-- /.box-header -->
                                <div class="box-body">                                
                                    <table id="example1" class="table table-bordered table-hover">
                                        <thead>
                                            <tr>
                                                <th class="arredondarEsq">ID</th>
												<th >SERVIÇO</th>
												<th >PROJETO</th>
												<th >DATA</th>
												<th >CARGA HORÁRIA</th>
												<th>AÇÃO</th>
                                                
                                            </tr>
                                        </thead>
                                        <tbody>
                                        <?php if(count($this->listaServicos)>0){
											foreach($this->listaServicos as $servico) : ?>
                                            <tr>
                                            <td><?php echo $servico["ID_SERVICO"]?></td>
                                            <td><?php echo $servico["DS_SERVICO"]?></td>
											<td><a alt="Editar" title="Editar" href="<?php echo $this->url(array('controller'=>'index','action'=>'view-projeto', 'id'=>$servico["FK_PROJETO"]),null, true);?>" class=""><?php echo $servico["NM_PROJETO"]?></a></td>
											<td><?php echo $servico["DT_SERVICO"]?></td>
											<td><?php echo $servico["NR_CARGA_HORARIA"]?></td>
                                             <td>
                                                <a alt="Editar" title="Editar" href="<?php echo $this->url(array('controller'=>'index','action'=>'edit-servico', 'id'=>$servico["ID_SERVICO"]),null, true);?>" class="btn-sm btn-warning"><i class="glyphicon glyphicon-edit"></i></a> 
                                                 <a alt="Excluir" title="Excluir" href="<?php echo $this->url(array('controller'=>'index','action'=>'delete-servico', 'id'=>$servico["ID_SERVICO"]),null, true);?>" class="btn-sm  btn-danger"><i class="glyphicon glyphicon-trash"></i></a>
                                                
                                                </td>
                                            </tr>
                                          <?php endforeach; ?>
	<?php }?> 
                                        </tbody>
                                        <tfoot>
                                            <tr>
                                                <th class="arredondarEsq">ID</th>
												<th >SERVIÇO</th>
												<th >PROJETO</th>
												<th >DATA</th>
												<th >CARGA HORÁRIA</th>
												<th>AÇÃO</th>                                      
                                            </tr>
                                        </tfoot>
                                    </table>
                                </div><!-- /.box-body -->
                            </div><!-- /.box -->
                            <div class="form-group">
                                 <a alt="Adicionar" title="Adicionar" style="font-family: inherit;" href="<?php echo $this->url(array('controller'=>'index','action'=>'add-servico'),null, true);?>" class="btn-sm  "><i class="btn btn-primary">Adicionar Serviço</i></a>   		
                                     		

                                    		</div>
<link href="<?php echo $this->baseUrl()?>/plugins/datatables/dataTables.bootstrap.css" rel="stylesheet" type="text/css" />
<script src="<?php echo $this->baseUrl()?>/plugins/datatables/jquery.dataTables.min.js" ></script>
<script src="<?php echo $this->baseUrl()?>/plugins/datatables/dataTables.bootstrap.min.js" ></script>
<!-- page script -->
<script type="text/javascript">
            $(function() {
                $("#example1").dataTable();
				//$("#example2").dataTable();
                /*$('#example2').dataTable({
                    "bPaginate": true,
                    "bLengthChange": false,
                    "bFilter": true,
                    "bSort": true,
                    "bInfo": true,
                    "bAutoWidth": false
                });*/
            });
</script>
