<?php
	$this->title = "Listar Contato";
	$this->headTitle($this->title);
	//echo $this->form ;
	
?>

<div class="box">
                                <div class="box-header">
                                    <h3 class="box-title">Lista Contato</h3>
                                </div><!-- /.box-header -->
                                <div class="box-body">                                
                                    <table id="example1" class="table table-bordered table-hover box-body table-responsive no-padding">
                                        <thead>
                                            <tr>
                                                <th class="arredondarEsq">OPERADORES</th>
												<th >PA</th>
												<th>CONTATOS</th>
												<th >DOCS</th>
												<th >SERVIÇOS</th>
												<th >PCP</th>
												<th >CLIENTE</th>
												<th >NOME PROJETO</th>
												<th >TIPO</th>
												<th >DATA CADASTRO</th>
												<th >OBSERVAÇÃO</th>
												<th >STATUS</th>
												<th>AÇÃO</th>
                                                
                                            </tr>
                                        </thead>
                                        <tbody>
                                        <?php if(count($this->listaProjetos)>0){
											foreach($this->listaProjetos as $projeto) : ?>
                                            <tr>
                                            <td></td>
											<td></td>
											<td></td>
											<td></td>
											<td></td>
											<td></td>
											<td></td>
											<td><?php echo $projeto["NM_PROJETO"]?></td>
											<td></td>
											<td><?php echo $projeto["DT_CADASTRO"]?></td>
											<td><?php echo $this->truncate($projeto["TX_OBSERVACAO"],50)?></td>
											<td></td>
                                             <td>
                                                <a alt="Editar" title="Editar" href="<?php echo $this->url(array('controller'=>'index','action'=>'edit-projeto', 'id'=>$projeto["ID_CLIENTE"]),null, true);?>" class="btn-sm btn-warning"><i class="glyphicon glyphicon-edit"></i></a> 
                                                 <a alt="Excluir" title="Excluir" href="<?php echo $this->url(array('controller'=>'index','action'=>'delete-projeto', 'id'=>$projeto["ID_CLIENTE"]),null, true);?>" class="btn-sm  btn-danger"><i class="glyphicon glyphicon-trash"></i></a>
                                                
                                                </td>
                                            </tr>
                                          <?php endforeach; ?>
	<?php }?> 
                                        </tbody>
                                        <tfoot>
                                            <tr>
                                                <th class="arredondarEsq">OPERADORES</th>
												<th >PA</th>
												<th>CONTATOS</th>
												<th >DOCS</th>
												<th >SERVIÇOS</th>
												<th >PCP</th>
												<th >CLIENTE</th>
												<th >NOME PROJETO</th>
												<th >TIPO</th>
												<th >DATA CADASTRO</th>
												<th >OBSERVAÇÃO</th>
												<th >STATUS</th>
												<th>AÇÃO</th>
                                                                                             
                                            </tr>
                                        </tfoot>
                                    </table>
                                </div><!-- /.box-body -->
                            </div><!-- /.box -->
                            <div class="form-group">
                                 <a alt="Adicionar" title="Adicionar" style="font-family: inherit;" href="<?php echo $this->url(array('controller'=>'index','action'=>'add-cliente'),null, true);?>" class="btn-sm  "><i class="btn btn-primary">Adicionar Cliente</i></a>   		
                                     		

                                    		</div>
<link href="<?php echo $this->baseUrl()?>/plugins/datatables/dataTables.bootstrap.css" rel="stylesheet" type="text/css" />
<script src="<?php echo $this->baseUrl()?>/plugins/datatables/jquery.dataTables.min.js" ></script>
<script src="<?php echo $this->baseUrl()?>/plugins/datatables/dataTables.bootstrap.min.js" ></script>
<!-- page script -->
<script type="text/javascript">
            $(function() {
                $("#example1").dataTable();
				$("#example2").dataTable();
                /*$('#example2').dataTable({
                    "bPaginate": true,
                    "bLengthChange": false,
                    "bFilter": true,
                    "bSort": true,
                    "bInfo": true,
                    "bAutoWidth": false
                });*/
            });
</script>
