<?php
	$this->title = "Listar Contato";
	$this->headTitle($this->title);
	//echo $this->form ;
	
?>
              <div class="box">
                <div class="box-header">
                  <h3 class="box-title">Projeto</h3>
                  
                </div><!-- /.box-header -->
                <div class="box-body table-responsive no-padding">
                  <table class="table table-hover">
                    <tr>
                      <th>CLIENTE</th>
                      <th>NOME PROJETO</th>
                      <th>TIPO PROJETO</th>
                      <th>AGÊNCIA AMBIENTAL</th>
                      <th>OBS</th>
                      <th>STATUS</th>           
                    </tr>
                   
                    <tr>
                      <td><?php echo $this->projeto["NM_CLIENTE"]?></td>
                      <td><?php echo $this->projeto["NM_PROJETO"]?></td>
                      <td><?php echo $this->projeto["NM_TIPO_PROJETO"]?></td>
                      <td><?php echo $this->projeto["NM_AGENCIA_AMBIENTAL"]?></td>
                      <td><?php echo $this->projeto["TX_OBSERVACAO"]?></td>
                    <td><?php echo $this->projeto["NM_STATUS_PROJETO"]?></td>
                    </tr>
                   
                   
                  </table>
                </div><!-- /.box-body -->
              </div><!-- /.box -->
<div class="box">
                                <div class="box-header">
                                    <h3 class="box-title">Lista Operador</h3>
                                </div><!-- /.box-header -->
                                <div class="box-body">                                
                                    <table id="example1" class="table table-bordered table-hover">
                                        <thead>
                                            <tr>
                                                <th class="arredondarEsq">NOME</th>
												<th >E-MAIL</th>
												<th>AÇÃO</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                        <?php if(count($this->operador)>0){
											foreach($this->operador as $operador) : ?>
                                            <tr>
						                      <td><?php echo $operador["PRIMEIRO_NOME"]?></td>
						                      <td><?php echo $operador["DS_EMAIL_BIOS"]?></td>
						                                     
                                             <td>
                                                 
                                                   <a alt="Excluir" title="Excluir" href="<?php echo $this->url(array('controller'=>'index','action'=>'delete-projeto-operador', 'ID_PROJETO'=>$operador["ID_PROJETO"],'ID_OPERADOR'=>$operador["ID_OPERADOR"]),null, true);?>" class="btn-sm  btn-danger"><i class="glyphicon glyphicon-trash"></i></a>
                                               
                                                </td>
                                            </tr>
                                          <?php endforeach; ?>
	<?php }?> 
                                        </tbody>
                                        <tfoot>
                                            <tr>
                                               <th class="arredondarEsq">NOME</th>
												<th >E-MAIL</th>
												<th>AÇÃO</th>                                            
                                            </tr>
                                        </tfoot>
                                    </table>
                                </div><!-- /.box-body -->
                            </div><!-- /.box -->
                            <?php  if($this->permissaoAdicionarOperador){?>
                             <div class="form-group">
                                 <a alt="Adicionar" title="Adicionar" style="font-family: inherit;" href="<?php echo $this->url(array('controller'=>'index','action'=>'add-projeto-operador','id'=>$this->projeto["ID_PROJETO"]),null, true);?>" class="btn-sm  "><i class="btn btn-primary">Adicionar Operador</i></a>   		
                                     		

                                    		</div> 
                             <?php }?> 
<link href="<?php echo $this->baseUrl()?>/plugins/datatables/dataTables.bootstrap.css" rel="stylesheet" type="text/css" />
<script src="<?php echo $this->baseUrl()?>/plugins/datatables/jquery.dataTables.min.js" ></script>
<script src="<?php echo $this->baseUrl()?>/plugins/datatables/dataTables.bootstrap.min.js" ></script>
<!-- page script -->
<script type="text/javascript">
            $(function() {
                $("#example1").dataTable();
				$("#example2").dataTable();
                /*$('#example2').dataTable({
                    "bPaginate": true,
                    "bLengthChange": false,
                    "bFilter": true,
                    "bSort": true,
                    "bInfo": true,
                    "bAutoWidth": false
                });*/
            });
</script>
