    <?php
           // $this->title = "Adicionar novo Bar";
            $this->headTitle($this->title);
          echo $this->form ;
    ?>
    	<?php if ($this->mensagem !=""){?>
    <div class="login-box" style="margin:auto;width: 360px;">
      <div class="callout callout-danger">
                    <h4>Erro!</h4>
                    <p><?php  echo $this->mensagem?></p>
                    	<p><?php //echo $this->mensagemExcecao?></p>
                  </div>
    </div><!-- /.login-box -->
<?php }?>