
<?php
	$this->title = "Criar Serviço";
	$this->headTitle($this->title);
?>
<?php if(!$this->validarServico){?>
<div class="callout callout-warning">
                                        <h4>Atenção!</h4>
                                        Deseja realmente criar um serviço através do PCP  '<?php echo $this->escape($this->servico['DS_SERVICO']);?>' ?
                                    </div>
<form action="<?php echo $this->url(array('action' => 'validar-servico','id'=>$this->servico['ID_SERVICO']),null, true);?>" method="post">
	<div>
		<input type="hidden" name="ID_SERVICO" value="<?php echo $this->servico['ID_SERVICO'];?>" /> 
		
	</div>
	<div class="form-group">
                                        		
<input type="submit" class="btn btn-primary"name="del" value="Sim">                                        		
<input type="submit" class="btn btn-primary"    name="del" value="Não">                                        		

                                    		</div>
</form>

<?php }else{?>
	<form action="#" method="post">
	                                     		
<input type="submit" class="btn btn-primary"    name="del" value="Voltar">                                        		
   
<a style="color:#fff;font-weight: bold;" alt="Editar" title="Editar" href="<?php echo $this->url(array('controller'=>'index','action'=>'edit-servico', 'id'=>$this->ID_SERVICO),null, true)?>" class="btn btn-default btn-warning">EDITAR SERVIÇO</a> 
</form>
	<?php }?>
