<ul class="sidebar-menu">
                        <li style="display: none">
                            <a href="../../index.html">
                                <i class="fa fa-dashboard"></i> <span>Dashboard</span>
                            </a>
                        </li>
                       
                     
                          <?php    //if ($this->fk_perfil!=2){?>  <li class="treeview">
                            <a href="#">
                                <i class="fa fa-th"></i>
                                <span>Projeto</span>
                                <i class="fa fa-angle-left pull-right"></i>
                            </a>
                            <ul class="treeview-menu">
                                <li><a href="<?php echo $this->url(array('controller'=>'index','action'=>'add-projeto'),null, true);?>"><i class="fa fa-angle-double-right"></i>Adicionar Projeto</a></li>
                                
                                
                            </ul>
                        </li> <?php //}?>
                         <?php    if ($this->fk_perfil!=2){?>  <li class="treeview">
                            <a href="#">
                                <i class="fa fa-th"></i>
                                <span>Usuário</span>
                                <i class="fa fa-angle-left pull-right"></i>
                            </a>
                            <ul class="treeview-menu">
                                <li><a href="<?php echo $this->url(array('controller'=>'index','action'=>'lista-usuario'),null, true);?>"><i class="fa fa-angle-double-right"></i> Listar Usuário</a></li>
                                <li><a href="<?php echo $this->url(array('controller'=>'index','action'=>'add-usuario'),null, true);?>"><i class="fa fa-angle-double-right"></i> Adicionar Usuário</a></li>
                                
                            </ul>
                        </li> <?php }?>
                       
                    </ul>
