	<!-- Small boxes (Stat box) -->
	
				<div class="box box-default">
				<form role="form" action="" method="<?php echo $this->element->getMethod() ?>" id="<?php echo $this->element->getName()?>" enctype="multipart/form-data">           
            <div class="box-header with-border">
			
			
              <h3 class="box-title">OPERADOR</h3>
              <div class="box-tools pull-right">
                <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-remove"></i></button>
              </div>
            </div><!-- /.box-header -->
		   <div class="box-body">
              <div class="row">
			  
                <div class="col-md-12">
				<?php echo $this->element->ID_CLIENTE ?>
					<div class="form-group">
								                      <label >NOME</label>
								                      <?php echo $this->element->nome ?>
								                     
								                  </div> 
								                  <div class="form-group">
														<label>E-MAIL</label>
														 <?php echo $this->element->email ?>
										           </div><!-- /input-group -->
								                  <div class="form-group">
								                      <label >LOGIN</label>
								                      <?php echo $this->element->login ?>
								                  </div>
								                  <div class="form-group">
								                      <label >SENHA</label>
								                      <?php echo $this->element->senha ?>
								                  </div>
								                  <div class="form-group">
								                      <label >REPETIR SENHA</label>
								                      <?php echo $this->element->repetirSenha?>
								                  </div>   
								                  <div class="form-group">
														<label>PERFIL</label>
														 <?php echo $this->element->fk_perfil ?>
										               
										           </div><!-- /input-group -->
										           
								                   <div class="form-group">
								                      <label >FOTO</label>
								                      <?php echo $this->element->fileUpload ?>
								                  </div>
								                  
     
                </div><!-- /.col --> 
             
			  </div><!-- /.row -->
            </div><!-- /.box-body -->
           <div class="box-footer">
                    <button class="btn btn-default" type="submit" name="Voltar">Voltar</button>
                    <button class="btn btn-info pull-right" type="submit" name="Salvar">Salvar</button>
                  </div>
				   </form>
          </div><!-- /.box -->
            <script>
      $(function () {
        //Initialize Select2 Elements
        $(".select2").select2();

        $('#data_cadastro').datepicker({
            format: 'mm/dd/yyyy',
            startDate: '-3d'
        });
        
      });
    </script>
		   