	<!-- Small boxes (Stat box) -->
	
				<div class="box box-default">
				<form role="form" action="" method="<?php echo $this->element->getMethod() ?>" id="<?php echo $this->element->getName()?>" enctype="multipart/form-data">           
            <div class="box-header with-border">
			
			
              <h3 class="box-title">CLIENTE</h3>
              <div class="box-tools pull-right">
                <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-remove"></i></button>
              </div>
            </div><!-- /.box-header -->
		   <div class="box-body">
              <div class="row">
			  
                <div class="col-md-12">
				<?php echo $this->element->ID_CLIENTE ?>
					<div class="form-group">
								                      <label >NOME</label>
								                      <?php echo $this->element->NM_CLIENTE ?>
								                     
								                  </div>
								                  <div class="form-group">
								                      <label >CNPJ</label>
								                      <?php echo $this->element->NR_CNPJ ?>
								                  </div>
								                  <div class="form-group">
														<label>RAMO ATIVIDADE</label>
														 <?php echo $this->element->FK_RAMO_ATIVIDADE ?>
										           </div><!-- /input-group -->
								                  <div class="form-group">
								                      <label >OBSERVAÇÃO</label>
								                      <?php echo $this->element->TX_OBSERVACAO ?>
								                  </div>
								                  <div class="form-group">
								                      <label >LOGRADOURO</label>
								                      <?php echo $this->element->NM_LOGRADOURO ?>
								                  </div>
								                  <div class="form-group">
								                      <label >NÚMERO</label>
								                      <?php echo $this->element->NR_NUMERO?>
								                  </div>
								                  <div class="form-group">
								                      <label >COMPLEMENTO</label>
								                      <?php echo $this->element->DS_COMPLEMENTO ?>
								                  </div>
								                  <div class="form-group">
								                      <label >BAIRRO</label>
								                      <?php echo $this->element->NM_BAIRRO ?>
								                  </div>
								                   <div class="form-group">
								                      <label >CEP</label>
								                      <?php echo $this->element->NR_CEP ?>
								                  </div>
								                   <div class="form-group">
								                      <label >CIDADE</label>
								                      <?php echo $this->element->NM_CIDADE ?>
								                  </div>
								                   <div class="form-group">
								                      <label >MUNICIPIO/UF</label>
								                      
								                      <?php echo $this->element->NM_UF ?>
								                   </div>
								                   <div class="form-group">
								                      <label >DATA ÚLTIMA ATUALIZAÇÃO</label>
								                      <input type="text" class="form-control" id="data_atualizacao" name="data_atualizacao" placeholder="" value="01/02/2016 22:50:37" disabled="disabled">
								                  </div>
     
                </div><!-- /.col --> 
             
			  </div><!-- /.row -->
            </div><!-- /.box-body -->
           <div class="box-footer">
                    <button class="btn btn-default" type="submit" name="Voltar">Voltar</button>
                    <button class="btn btn-info pull-right" type="submit" name="Salvar">Salvar</button>
                  </div>
				   </form>
          </div><!-- /.box -->
            <script>
      $(function () {
        //Initialize Select2 Elements
        $(".select2").select2();

        $('#data_cadastro').datepicker({
            format: 'mm/dd/yyyy',
            startDate: '-3d'
        });
        
      });
    </script>
		   