	<!-- Small boxes (Stat box) -->
				<div class="box box-default">
				<form role="form" action="" method="<?php echo $this->element->getMethod() ?>" id="<?php echo $this->element->getName()?>" enctype="multipart/form-data">
            <div class="box-header with-border">
              <h3 class="box-title">ADICIONAR SERVIÇO</h3>
              <div class="box-tools pull-right">
                <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-remove"></i></button>
              </div>
            </div><!-- /.box-header -->
            <div class="box-body">
              <div class="row">
                <div class="col-md-12">
                
					
						 <div class="form-group">
						<label>PROJETO</label>
		                <select class="form-control select2" style="width: 100%;" name="FK_PROJETO" id="FK_PROJETO"  >
	                      <option selected="selected">PROJETO A</option>
	                      <option>PROJETO B</option>
	                      <option>xxxxxxx C</option>
	                      <option>yyyyyyyyyyy D</option>
	                      <option>bbbbbbbbbb E</option>
	                      <option>ffffff F</option>
	                      <option>kkkkkkk G</option>
	                    </select>
		                  
	                    </div><!-- /input-group -->
	                    <div class="form-group">
	                      <label>DESCRIÇÃO SERVIÇO</label>
	                      <textarea class="form-control" rows="3" name="observacao" id="observacao" placeholder="Enter ..."></textarea>
	                  	</div>
	                  	<div class="form-group">
	                    <label>DATA</label>
	                    <div class="input-group">
	                      <div class="input-group-addon">
	                        <i class="fa fa-calendar"></i>
	                      </div>
	                      <input type="text" class="form-control pull-right" id="data_cadastro" name="data_cadastro" data-provide="datepicker">
	                    </div><!-- /.input group -->
	                  <div class="form-group">
	                      <label >CARGA HORÁRIA</label>
	                      <input type="text" class="form-control" id="nome" name="nome" placeholder="Carga horária">
	                  </div>
	                  <div class="form-group">
	                    <label>TIPO SERVIÇO</label>
	                    <select class="form-control select2" style="width: 100%;" name="fk_tipo_projeto" id="fk_tipo_projeto">
	                      <option selected="selected">Tipo serviço A</option>
	                      <option>Tipo serviço B</option>
	                      <option>xxxxxxx C</option>
	                      <option>yyyyyyyyyyy D</option>
	                      <option>bbbbbbbbbb E</option>
	                      <option>ffffff F</option>
	                      <option>kkkkkkk G</option>
	                    </select>
	                  </div><!-- /.form-group -->
	                 
	                  </div><!-- /.form group -->
	                   
                  
                </div><!-- /.col --> 
              </div><!-- /.row -->
            </div><!-- /.box-body -->
           <div class="box-footer">
                    <button class="btn btn-default" type="submit">Voltar</button>
                    <button class="btn btn-info pull-right" type="submit">Salvar</button>
                  </div>
                   </form>
          </div><!-- /.box -->