	<!-- Small boxes (Stat box) -->
				<div class="box box-default">
				<form role="form" action="" method="<?php echo $this->element->getMethod() ?>" id="<?php echo $this->element->getName()?>" enctype="multipart/form-data">
            <div class="box-header with-border">
              <h3 class="box-title">ADICIONAR PA</h3>
              <div class="box-tools pull-right">
                <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-remove"></i></button>
              </div>
            </div><!-- /.box-header -->
            <div class="box-body">
              <div class="row">
                <div class="col-md-12">
                	 
       
       
       
       
       
       
       
       
       
        <?php echo $this->element->ID_PLANO_ACAO ?>
                <div class="form-group">
						<label ><?php echo $this->element->DS_ASSUNTO->getLabel() ?></label>
						<?php echo $this->element->DS_ASSUNTO ?>				                     
				</div>
				 <div class="form-group">
						<label ><?php echo $this->element->TX_PLANO_ACAO->getLabel() ?></label>
						<?php echo $this->element->TX_PLANO_ACAO ?>				                     
				</div>
				 <div class="form-group">
						<label ><?php echo $this->element->FK_PROJETO->getLabel() ?></label>
						<?php echo $this->element->FK_PROJETO ?>				                     
				</div>
				
				<div class="form-group">
						<label ><?php echo $this->element->FK_STATUS_PLANO_ACAO->getLabel() ?></label>
						<?php echo $this->element->FK_STATUS_PLANO_ACAO ?>				                     
				</div>
				<div class="form-group">
						<label ><?php echo $this->element->FK_OPERADOR->getLabel() ?></label>
						<?php echo $this->element->FK_OPERADOR ?>				                     
				</div>
				<div class="form-group">
	                    <label><?php echo $this->element->DT_PREVISAO->getLabel() ?></label>
	                    <div class="input-group">
	                      <div class="input-group-addon">
	                        <i class="fa fa-calendar"></i>
	                      </div>
	                      <?php echo $this->element->DT_PREVISAO ?>		
	                     
	                    </div><!-- /.input group -->
	            </div><!-- /.form group -->
	            <div class="form-group">
	                    <label><?php echo $this->element->DT_CONTROLE->getLabel() ?></label>
	                    <div class="input-group">
	                      <div class="input-group-addon">
	                        <i class="fa fa-calendar"></i>
	                      </div>
	                      <?php echo $this->element->DT_CONTROLE ?>		
	                     
	                    </div><!-- /.input group -->
	            </div><!-- /.form group -->
	            <div class="form-group">
	                    <label><?php echo $this->element->DT_CONCLUSAO->getLabel() ?></label>
	                    <div class="input-group">
	                      <div class="input-group-addon">
	                        <i class="fa fa-calendar"></i>
	                      </div>
	                      <?php echo $this->element->DT_CONCLUSAO ?>		
	                     
	                    </div><!-- /.input group -->
	            </div><!-- /.form group -->
	                  	
	                 
	                  
	                 
	
	                   
                  
                </div><!-- /.col --> 
              </div><!-- /.row -->
            </div><!-- /.box-body -->
           <div class="box-footer">
                   <button class="btn btn-default" type="submit" name="Voltar">Voltar</button>
                    <button class="btn btn-info pull-right" type="submit" name="Salvar">Salvar</button>
                  </div>
                   </form>
          </div><!-- /.box -->
          <script>
      $(function () {
        //Initialize Select2 Elements
        $(".select2").select2();

        $('.data').datepicker({
            format: 'dd/mm/yyyy'
        });
        
      });
    </script>