	<!-- Small boxes (Stat box) -->
				<div class="box box-default">
				<form role="form" action="" method="<?php echo $this->element->getMethod() ?>" id="<?php echo $this->element->getName()?>" enctype="multipart/form-data">
            <div class="box-header with-border">
              <h3 class="box-title">ADICIONAR SERVIÇO</h3>
              <div class="box-tools pull-right">
                <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-remove"></i></button>
              </div>
            </div><!-- /.box-header -->
            <div class="box-body">
              <div class="row">
                <div class="col-md-12">
                
					
					  <div class="form-group">
	                      <label ><?php echo $this->element->FK_PROJETO->getLabel() ?></label>
	                     <?php echo $this->element->FK_PROJETO ?>
	                  </div>
	                   <div class="form-group">
	                      <label ><?php echo $this->element->DS_SERVICO->getLabel() ?></label>
	                     <?php echo $this->element->DS_SERVICO ?>
	                  </div>
	                  	<div class="form-group">
	                    <label><?php echo $this->element->DT_SERVICO->getLabel() ?></label>
	                    <div class="input-group">
	                      <div class="input-group-addon">
	                        <i class="fa fa-calendar"></i>
	                      </div>
	                      <?php echo $this->element->DT_SERVICO ?>		
	                     
	                    </div><!-- /.input group -->
	           		  </div><!-- /.form group -->
	                  <div class="form-group">
	                      <label ><?php echo $this->element->NR_CARGA_HORARIA->getLabel() ?></label>
	                     <?php echo $this->element->NR_CARGA_HORARIA ?>
	                  </div>
	                  <div class="form-group">
	                      <label ><?php echo $this->element->FK_TIPO_SERVICO->getLabel() ?></label>
	                     <?php echo $this->element->FK_TIPO_SERVICO ?>
	                  </div>
	                 
	                  </div><!-- /.form group -->
	                   
                  
                </div><!-- /.col --> 
              </div><!-- /.row -->
            </div><!-- /.box-body -->
           <div class="box-footer">
                    <button class="btn btn-default" type="submit" name="Voltar">Voltar</button>
                    <button class="btn btn-info pull-right" type="submit" name="Salvar">Salvar</button>
                  </div>
                   </form>
          </div><!-- /.box -->
          <script>
      $(function () {
        //Initialize Select2 Elements
        $(".select2").select2();

        $('#DT_SERVICO').datepicker({
        	format: 'dd/mm/yyyy'
          
        });
        
      });
    </script>