	<!-- Small boxes (Stat box) -->
				<div class="box box-default">
				<form role="form" action="" method="<?php echo $this->element->getMethod() ?>" id="<?php echo $this->element->getName()?>" enctype="multipart/form-data">
            <div class="box-header with-border">
              <h3 class="box-title">NOTÍCIA</h3>
              <div class="box-tools pull-right">
                <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-remove"></i></button>
              </div>
            </div><!-- /.box-header -->
            <div class="box-body">
              <div class="row">
                <div class="col-md-12">
	                <?php echo $this->element->ID_NOTICIA ?>
	                <?php echo $this->element->FK_ARQUIVO ?>
	                <?php echo $this->element->FK_OPERADOR ?>
	                <?php echo $this->element->DT_NOTICIA ?>
	                
	                <div class="form-group">
							<label ><?php echo $this->element->DS_TITULO->getLabel() ?></label>
							<?php echo $this->element->DS_TITULO ?>				                     
					</div>
					<div class="form-group">
							<label ><?php echo $this->element->DS_RESUMO->getLabel() ?></label>
							<?php echo $this->element->DS_RESUMO ?>				                     
					</div>
					<div class="form-group">
							<label ><?php echo $this->element->TX_NOTICIA->getLabel() ?></label>
							<?php echo $this->element->TX_NOTICIA ?>				                     
					</div>
					<div class="form-group">
							<label ><?php echo $this->element->FK_TIPO_NOTICIA->getLabel() ?></label>
							<?php echo $this->element->FK_TIPO_NOTICIA ?>				                     
					</div>
					
						 
	           </div><!-- /.form group -->
	                   
                  
                </div><!-- /.col --> 
              </div><!-- /.row -->
            </div><!-- /.box-body -->
           <div class="box-footer">
                   <button class="btn btn-default" type="submit" name="Voltar">Voltar</button>
                    <button class="btn btn-info pull-right" type="submit" name="Salvar">Salvar</button>
                  </div>
                   </form>
          </div><!-- /.box -->
         
          <link rel="stylesheet" href="<?php echo $this->baseUrl().'/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css'?>">
          <script src="<?php echo $this->baseUrl().'/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js'?>"></script>
          <script>
      $(function () {
        //Initialize Select2 Elements
        $(".select2").select2();

         $("#TX_NOTICIA").wysihtml5();
        
      });
    </script>