	<!-- Small boxes (Stat box) -->
				<div class="box box-default">
				<form role="form" action="" method="<?php echo $this->element->getMethod() ?>" id="<?php echo $this->element->getName()?>" enctype="multipart/form-data">
            <div class="box-header with-border">
              <h3 class="box-title">ADICIONAR PA</h3>
              <div class="box-tools pull-right">
                <button class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i></button>
                <button class="btn btn-box-tool" data-widget="remove"><i class="fa fa-remove"></i></button>
              </div>
            </div><!-- /.box-header -->
            <div class="box-body">
              <div class="row">
                <div class="col-md-12">
                	
					<div class="form-group">
	                      <label>ASSUNTO</label>
	                       <input type="text" class="form-control" id="DS_ASSUNTO" name="DS_ASSUNTO" placeholder="Enter cnpj" value="<?php /*echo $this->element->ds_assunto->getValue();*/?>">
	                </div>
					<div class="form-group">
	                      <label>AÇÕES</label>
	                      <textarea class="form-control" rows="3" name="TX_PLANO_ACAO" id="TX_PLANO_ACAO" ><?php /*echo $this->element->ds_assunto->getValue();*/?></textarea>
	                 </div>
					<div class="form-group">
	                      <label>CLIENTE</label>
	                       <input type="text" class="form-control" id="NM_CLIENTE"  name="NM_CLIENTE"  value="<?php /*echo $this->element->nm_cliente->getValue();*/?>">
	                </div>
					<div class="form-group">
						<label>STATUS</label>
		                <select class="form-control select2" style="width: 100%;" name="FK_STATUS" id="FK_STATUS"  >
	                      <option selected="selected">PROJETO A</option>
	                      <option>PROJETO B</option>
	                      <option>xxxxxxx C</option>
	                      <option>yyyyyyyyyyy D</option>
	                      <option>bbbbbbbbbb E</option>
	                      <option>ffffff F</option>
	                      <option>kkkkkkk G</option>
	                    </select>    
	                </div><!-- /input-group -->
					<div class="form-group">
						<label>OPERADOR</label>
		                <select class="form-control select2" style="width: 100%;" name="FK_OPERADOR" id="FK_OPERADOR"  >
	                      <option selected="selected">OPERADOR A</option>
	                      <option>PROJETO B</option>
	                      <option>xxxxxxx C</option>
	                      <option>yyyyyyyyyyy D</option>
	                      <option>bbbbbbbbbb E</option>
	                      <option>ffffff F</option>
	                      <option>kkkkkkk G</option>
	                    </select>    
	                </div><!-- /input-group -->
	                <div class="form-group">
	                    <label>ATUALIZAÇÃO</label>
	                    <div class="input-group">
	                      <div class="input-group-addon">
	                        <i class="fa fa-calendar"></i>
	                      </div>
	                      <input type="text" class="form-control pull-right" id="DT_ATUALIZACAO" name="DT_ATUALIZACAO" data-provide="datepicker">
	                </div><!-- /.input group -->
	                </div>
	                <div class="form-group">
	                    <label>PREVISAO</label>
	                    <div class="input-group">
	                      <div class="input-group-addon">
	                        <i class="fa fa-calendar"></i>
	                      </div>
	                      <input type="text" class="form-control pull-right" id="DT_PREVISAO" name="DT_PREVISAO" data-provide="datepicker">
	                </div><!-- /.input group -->
	                </div>
	                <div class="form-group">
	                    <label>CONTROLE</label>
	                    <div class="input-group">
	                      <div class="input-group-addon">
	                        <i class="fa fa-calendar"></i>
	                      </div>
	                      <input type="text" class="form-control pull-right" id="DT_CONTROLE" name="DT_CONTROLE" data-provide="datepicker">
	                 </div><!-- /.input group -->
	                 </div>
					
					 
	                    
	                  	
	                 
	                  
	                 
	
	                   
                  
                </div><!-- /.col --> 
              </div><!-- /.row -->
            </div><!-- /.box-body -->
           <div class="box-footer">
                    <button class="btn btn-default" type="submit">Voltar</button>
                    <button class="btn btn-info pull-right" type="submit">Salvar</button>
                  </div>
                   </form>
          </div><!-- /.box -->